// The state matrix both the prototype and the port are evaluated over.
export const CASES = {
  'welcome-0':      { screen: 'welcome', slide: 0 },
  'welcome-2':      { screen: 'welcome', slide: 2 },
  'login':          { screen: 'login' },
  'login-filled':   { screen: 'login', username: 'user', password: 'Password1!' },
  'signup':         { screen: 'signup' },
  'signup-weak':    { screen: 'signup', suUser: 'a', suEmail: 'a@b.co', suPass: 'abc', suConfirm: 'abc' },
  'signup-strong':  { screen: 'signup', suUser: 'a', suEmail: 'a@b.co', suPass: 'Password1!', suConfirm: 'Password1!', suTerms: true },
  'forgot-email':   { screen: 'forgot', fpStage: 'email' },
  'forgot-code':    { screen: 'forgot', fpStage: 'code', fpEmail: 'a@b.co', fpCode: '123456' },
  'forgot-reset':   { screen: 'forgot', fpStage: 'reset', fpPass: 'Password1!', fpConfirm: 'Password1!' },
  'forgot-done':    { screen: 'forgot', fpStage: 'done' },
  'dash-user':      { screen: 'dash', role: 'user' },
  'dash-admin':     { screen: 'dash', role: 'admin' },
  'dash-new':       { screen: 'dash', role: 'new' },
  'lost-user':      { screen: 'lost', role: 'user' },
  'found-user':     { screen: 'found', role: 'user' },
  'found-filter':   { screen: 'found', role: 'user', filter: 'Active' },
  'found-myposts':  { screen: 'found', role: 'user', filter: 'My posts' },
  'lost-myposts':   { screen: 'lost', role: 'user', filter: 'My posts' },
  'found-search':   { screen: 'found', role: 'user', q: 'watch' },
  'found-nohit':    { screen: 'found', role: 'user', q: 'zzzz' },
  'registry-admin': { screen: 'lost', role: 'admin' },
  'forum-user':     { screen: 'forum', role: 'user' },
  'forum-admin':    { screen: 'forum', role: 'admin' },
  'forum-topic':    { screen: 'forum', role: 'user', topic: 'Question' },
  'moderation':     { screen: 'moderation', role: 'admin' },
  'analysis':       { screen: 'analysis', role: 'admin' },
  'members':        { screen: 'members', role: 'admin' },
  'members-search': { screen: 'members', role: 'admin', uq: 'emily' },
  'messages':       { screen: 'messages', role: 'user' },
  'ads':            { screen: 'ads', role: 'admin' },
  'sheet-detail':   { screen: 'found', role: 'user', sheet: 'detail', sel: 'FOUND-2015' },
  'sheet-owner':    { screen: 'lost', role: 'user', sheet: 'detail', sel: 'LOST-1024' },
  'sheet-reunited': { screen: 'lost', role: 'user', sheet: 'detail', sel: 'LOST-1018' },
  'sheet-chat':     { screen: 'messages', role: 'user', sheet: 'chat', activeConvo: 'FOUND-2015' },
  'sheet-thread':   { screen: 'forum', role: 'user', sheet: 'thread', activeThread: 1 },
  'sheet-newthread':{ screen: 'forum', role: 'user', sheet: 'newthread', ntTag: 'Sighting' },
  'sheet-support':  { screen: 'dash', role: 'user', sheet: 'support' },
  'sheet-profile-u':{ screen: 'dash', role: 'user', sheet: 'profile' },
  'sheet-profile-a':{ screen: 'dash', role: 'admin', sheet: 'profile' },
  'sheet-profile-n':{ screen: 'dash', role: 'new', sheet: 'profile' },
  'sheet-guidelines':{ screen: 'dash', role: 'new', sheet: 'guidelines' },
  'sheet-report-1': { screen: 'dash', role: 'user', sheet: 'report', step: 1, rType: 'Lost' },
  'sheet-report-2': { screen: 'dash', role: 'user', sheet: 'report', step: 2, rType: 'Found', rTitle: 'X', rCat: 'Keys', rPlace: 'Y' },
  'sheet-sent':     { screen: 'dash', role: 'user', sheet: 'sent', newId: 'LOST-1032' },
  'sheet-ad':       { screen: 'ads', role: 'admin', sheet: 'ad', adEditId: 'AD-02', adDraft: { campaignKey: 'trackr', days: 14 } },
};
